// Generated by CoffeeScript 1.6.3
var TimerView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TimerView = (function(_super) {
  var PART_WIDTH;

  __extends(TimerView, _super);

  PART_WIDTH = 48;

  function TimerView(x, y) {
    TimerView.__super__.constructor.call(this, {
      x: x,
      y: y,
      partWidth: PART_WIDTH,
      count: 13,
      height: 8,
      foregroundImage: R.BACKGROUND_IMAGE.TIMER,
      backgroundImage: R.BACKGROUND_IMAGE.HP_ENCLOSE
    });
  }

  TimerView.prototype.initEvent = function(world) {
    var _this = this;
    world.addEventListener("ontimer", function(evt) {
      return _this.decreaseForce(PART_WIDTH / 8);
    });
    return world.addEventListener("gameend", function(evt) {
      return _this.increaseForce(PART_WIDTH * 13);
    });
  };

  return TimerView;

})(MeterView);
