// Generated by CoffeeScript 1.6.3
(function() {
  var arg, d, s, _i, _len, _results;
  s = document.getElementsByTagName("script");
  d = s[s.length - 1].src.substring(0, s[s.length - 1].src.lastIndexOf("/") + 1);
  _results = [];
  for (_i = 0, _len = arguments.length; _i < _len; _i++) {
    arg = arguments[_i];
    _results.push(document.write('<script type="text/javascript" src="' + d + arg + '"></script>'));
  }
  return _results;
})("third_party/underscore-min.js", "third_party/mt.js", "config.js", "utility/util.js", "utility/debug.js", "effect.js", "bullet.js", "item.js", "robot.js", "enchantAI/instr.js", "view.js", "main.js");
