// Generated by CoffeeScript 1.6.3
var TipBasedVPL,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TipBasedVPL = (function(_super) {
  __extends(TipBasedVPL, _super);

  function TipBasedVPL(w, h, resourceBase) {
    TipBasedVPL.__super__.constructor.call(this, w, h);
    this.fps = 24;
    this.octagrams = new OctagramSet(16, 16, 8, 8);
    Resources.base = resourceBase;
    Resources.load(this);
  }

  TipBasedVPL.prototype.onload = function() {
    var x, xnum, y, ynum;
    x = 16;
    y = 16;
    xnum = 8;
    ynum = 8;
    Game.instance.vpl = {};
    return Game.instance.vpl.currentVM = new Octagram(x, y, xnum, ynum);
  };

  return TipBasedVPL;

})(Game);
