// Generated by CoffeeScript 1.6.3
var TransitionEvent,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TransitionEvent = (function(_super) {
  __extends(TransitionEvent, _super);

  function TransitionEvent(type, params) {
    this.params = params;
    TransitionEvent.__super__.constructor.call(this, type);
  }

  return TransitionEvent;

})(enchant.Event);
