// Generated by CoffeeScript 1.6.3
var Maze,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Maze = (function(_super) {
  __extends(Maze, _super);

  function Maze(data) {
    Maze.__super__.constructor.apply(this, arguments);
    this.x = data.x != null ? data.x : 0;
    this.y = data.y != null ? data.y : 0;
    if (data.map == null) {
      data.map = map;
    }
    this.mazeMap = new MazeMap(data.map);
    this.addChild(this.mazeMap);
    this.player = new RobotPlayer(this.mazeMap);
    this.addChild(this.player);
    this.player.addEventListener('goal', function(evt) {
      return console.log("goal");
    });
  }

  return Maze;

})(Group);
