// Generated by CoffeeScript 1.3.3
var Command, CommandIterator;

Command = (function() {

  function Command(instruction, args) {
    this.instruction = instruction;
    this.args = args != null ? args : null;
  }

  Command.prototype["eval"] = function(robot) {
    return this.instruction.func.apply(robot, this.args);
  };

  return Command;

})();

CommandIterator = (function() {

  function CommandIterator(collection) {
    this.collection = collection;
    this.i = 0;
  }

  CommandIterator.prototype.next = function() {
    if (this.hasNext() === true) {
      return this.collection[this.i++];
    }
  };

  CommandIterator.prototype.hasNext = function() {
    return this.collection.length > this.i;
  };

  return CommandIterator;

})();
