// Generated by CoffeeScript 1.6.2
var DualPickupInstruction, GetBulletQueueSize, GetHp, MOVE_STR, MoveInstruction, NormalPickupInstruction, Pickup, PickupInstruction, R, RobotInstruction, SHOT_STR, Searching, ShotInstruction, WidePickupInstruction,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

R = Config.R;

MOVE_STR = R.String.INSTRUCTION.MOVE;

SHOT_STR = R.String.INSTRUCTION.SHOT;

RobotInstruction = (function() {
  function RobotInstruction() {}

  RobotInstruction.MOVE = "move";

  RobotInstruction.SHOT = "shot";

  RobotInstruction.PICKUP = "pickup";

  RobotInstruction.SEARCH = "search";

  RobotInstruction.GET_HP = "getHp";

  RobotInstruction.GET_BULLET_QUEUE_SIZE = "getBulletQueueSize";

  return RobotInstruction;

})();

MoveInstruction = (function(_super) {
  __extends(MoveInstruction, _super);

  MoveInstruction.direct = [Direct.RIGHT, Direct.RIGHT | Direct.UP, Direct.RIGHT | Direct.DOWN, Direct.LEFT, Direct.LEFT | Direct.UP, Direct.LEFT | Direct.DOWN];

  MoveInstruction.frame = [0, 4, 5, 2, 6, 7];

  function MoveInstruction(robot) {
    var parameter;

    this.robot = robot;
    MoveInstruction.__super__.constructor.apply(this, arguments);
    this.setAsynchronous(true);
    parameter = new TipParameter(MOVE_STR.colnum(), 0, 0, 6, 1);
    this._id = 0;
    this.addParameter(parameter);
  }

  MoveInstruction.prototype.action = function() {
    var plate, ret;

    ret = true;
    this.robot.frame = MoveInstruction.frame[this.directId];
    plate = this.robot.map.getTargetPoision(this.robot.currentPlate, MoveInstruction.direct[this._id]);
    ret = this._move(plate);
    this.setAsynchronous(ret !== false);
    return this.robot.onCmdComplete(RobotInstruction.MOVE, ret);
  };

  MoveInstruction.prototype._move = function(plate) {
    var pos, ret,
      _this = this;

    ret = false;
    this.robot.prevPlate = this.robot.currentPlate;
    if ((plate != null) && plate.lock === false) {
      pos = plate.getAbsolutePos();
      this.robot.tl.moveTo(pos.x, pos.y, PlayerRobot.UPDATE_FRAME).then(function() {
        return _this.onComplete();
      });
      this.robot.currentPlate = plate;
      ret = new Point(plate.ix, plate.iy);
    } else {
      ret = false;
    }
    return ret;
  };

  MoveInstruction.prototype.onComplete = function() {
    this.robot.onAnimateComplete();
    return MoveInstruction.__super__.onComplete.apply(this, arguments);
  };

  MoveInstruction.prototype.clone = function() {
    var obj;

    obj = this.copy(new MoveInstruction(this.robot));
    obj._id = this._id;
    return obj;
  };

  MoveInstruction.prototype.onParameterChanged = function(parameter) {
    return this._id = parameter.value;
  };

  MoveInstruction.prototype.mkDescription = function() {
    return MOVE_STR.description[this._id](1);
  };

  return MoveInstruction;

})(ActionInstruction);

ShotInstruction = (function(_super) {
  var bltQueues;

  __extends(ShotInstruction, _super);

  bltQueues = null;

  function ShotInstruction(robot) {
    var parameter;

    this.robot = robot;
    ShotInstruction.__super__.constructor.apply(this, arguments);
    if (bltQueues === null) {
      bltQueues = [this.robot.bltQueue, this.robot.wideBltQueue, this.robot.dualBltQueue];
    }
    parameter = new TipParameter(MOVE_STR.colnum(), 0, 0, 2, 1);
    this._id = 0;
    this.addParameter(parameter);
    this.setAsynchronous(true);
  }

  ShotInstruction.prototype.action = function() {
    var b, queue, ret, _i, _len, _ref,
      _this = this;

    ret = false;
    queue = bltQueues[this._id];
    if (!queue.empty()) {
      _ref = queue.dequeue();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        b = _ref[_i];
        b.shot(this.robot.x, this.robot.y, this.robot.getDirect());
        this.robot.scene.world.bullets.push(b);
        this.robot.scene.world.insertBefore(b, this.robot);
        b.setOnDestoryEvent(function() {
          return _this.onComplete();
        });
        ret = b;
      }
    }
    this.setAsynchronous(ret !== false);
    return this.robot.onCmdComplete(RobotInstruction.SHOT, ret);
  };

  ShotInstruction.prototype.onComplete = function() {
    this.robot.onAnimateComplete();
    return ShotInstruction.__super__.onComplete.apply(this, arguments);
  };

  ShotInstruction.prototype.onParameterChanged = function(parameter) {
    return this._id = parameter.value;
  };

  ShotInstruction.prototype.clone = function() {
    var obj;

    obj = this.copy(new ShotInstruction(this.robot));
    obj._id = this._id;
    return obj;
  };

  ShotInstruction.prototype.mkDescription = function() {
    return SHOT_STR.description[this._id]();
  };

  return ShotInstruction;

})(ActionInstruction);

PickupInstruction = (function(_super) {
  __extends(PickupInstruction, _super);

  function PickupInstruction(robot, queue, type, itemClass, instrClass) {
    this.robot = robot;
    this.queue = queue;
    this.type = type;
    this.itemClass = itemClass;
    this.instrClass = instrClass;
    PickupInstruction.__super__.constructor.apply(this, arguments);
    this.setAsynchronous(true);
  }

  PickupInstruction.prototype.action = function() {
    var blt, item, ret,
      _this = this;

    blt = BulletFactory.create(this.type, this.robot);
    ret = this.queue.enqueue(blt);
    if (ret !== false) {
      item = new this.itemClass(this.robot.x, this.robot.y);
      this.robot.scene.world.addChild(item);
      this.robot.scene.world.items.push(item);
      item.setOnCompleteEvent(function() {
        return _this.onComplete();
      });
      ret = blt;
    }
    this.setAsynchronous(ret !== false);
    return this.robot.onCmdComplete(RobotInstruction.PICKUP, ret);
  };

  PickupInstruction.prototype.onComplete = function() {
    this.robot.onAnimateComplete();
    return PickupInstruction.__super__.onComplete.apply(this, arguments);
  };

  PickupInstruction.prototype.clone = function() {
    var instr;

    instr = new this.instrClass(this.robot);
    return instr;
  };

  return PickupInstruction;

})(ActionInstruction);

NormalPickupInstruction = (function(_super) {
  __extends(NormalPickupInstruction, _super);

  function NormalPickupInstruction(robot) {
    NormalPickupInstruction.__super__.constructor.call(this, robot, robot.bltQueue, BulletType.NORMAL, NormalBulletItem, NormalPickupInstruction);
  }

  NormalPickupInstruction.prototype.mkDescription = function() {
    return "NormalPickupInstruction";
  };

  return NormalPickupInstruction;

})(PickupInstruction);

WidePickupInstruction = (function(_super) {
  __extends(WidePickupInstruction, _super);

  function WidePickupInstruction(robot) {
    WidePickupInstruction.__super__.constructor.call(this, robot, robot.wideBltQueue, BulletType.WIDE, WideBulletItem, WidePickupInstruction);
  }

  WidePickupInstruction.prototype.mkDescription = function() {
    return "WidePickupInstruction";
  };

  return WidePickupInstruction;

})(PickupInstruction);

DualPickupInstruction = (function(_super) {
  __extends(DualPickupInstruction, _super);

  function DualPickupInstruction(robot) {
    DualPickupInstruction.__super__.constructor.call(this, robot, robot.dualBltQueue, BulletType.DUAL, DualBulletItem, DualPickupInstruction);
  }

  DualPickupInstruction.prototype.mkDescription = function() {
    return "DualPickupInstruction";
  };

  return DualPickupInstruction;

})(PickupInstruction);

Searching = (function(_super) {
  __extends(Searching, _super);

  function Searching() {
    Searching.__super__.constructor.call(this, RobotInstruction.SEARCH, this.func);
  }

  Searching.prototype.func = function() {
    var robot, world;

    world = this.scene.world;
    robot = this === world.player ? world.enemy : this;
    return new Point(robot.x - this.x, robot.y - this.y);
  };

  return Searching;

})(RobotInstruction);

Pickup = (function(_super) {
  __extends(Pickup, _super);

  function Pickup() {
    Pickup.__super__.constructor.call(this, RobotInstruction.PICKUP, this.func);
  }

  Pickup.prototype.func = function(type, itemClass, queue) {
    var blt, item, ret;

    blt = BulletFactory.create(type, this);
    ret = queue.enqueue(blt);
    if (ret !== false) {
      item = new itemClass(this.x, this.y);
      this.scene.world.addChild(item);
      this.scene.world.items.push(item);
      ret = blt;
    }
    return ret;
  };

  return Pickup;

})(RobotInstruction);

GetHp = (function(_super) {
  __extends(GetHp, _super);

  function GetHp() {
    GetHp.__super__.constructor.call(this, RobotInstruction.GET_HP, this.func);
  }

  GetHp.prototype.func = function() {
    return this.hp;
  };

  return GetHp;

})(RobotInstruction);

GetBulletQueueSize = (function(_super) {
  __extends(GetBulletQueueSize, _super);

  function GetBulletQueueSize() {
    GetBulletQueueSize.__super__.constructor.call(this, RobotInstruction.GET_BULLET_QUEUE_SIZE, this.func);
  }

  GetBulletQueueSize.prototype.func = function() {
    return this.bltQueue.size();
  };

  return GetBulletQueueSize;

})(RobotInstruction);
