// Generated by CoffeeScript 1.6.3
window.onload = function() {
  var colors, converter, moveToBattlePage, selector;
  selector = new ProgramSelector();
  moveToBattlePage = function(playerId, enemyId) {
    return location.href = getRoot() + "combats/matching/" + playerId + "/" + enemyId;
  };
  $('.program-row').click(function() {
    var name,
      _this = this;
    name = $(this).find('.program-name').text().replace(/^\s+|\s+$/g, "");
    return selector.modal({
      title: name + "と対戦するプログラムを選んで下さい。",
      buttons: [
        {
          type: "success",
          text: "Select",
          handler: function(data) {
            return moveToBattlePage(data.id, $(_this).attr('program-id'));
          }
        }
      ]
    });
  });
  colors = ['#aaaaaa', '#5cb85c', '#428bca', '#f0ad4e', '#d9534f'];
  converter = new ColorConverter(colors);
  $.each($('.rate'), function() {
    return $(this).css('color', converter.rateToColor($(this).text()));
  });
  $.each($('.battle_num'), function() {
    return $(this).css('color', converter.battleNumToColor($(this).text()));
  });
  return $.each($('.score_average'), function() {
    return $(this).css('color', converter.scoreToColor($(this).text()));
  });
};
