// Generated by CoffeeScript 1.6.3
window.onload = function() {
  var moveToBattlePage, selector;
  selector = new ProgramSelector();
  moveToBattlePage = function(playerId, enemyId) {
    return location.href = getRoot() + "combats/matching/" + playerId + "/" + enemyId;
  };
  $('.program-row').click(function() {
    var _this = this;
    return selector.modal({
      buttons: [
        {
          type: "success",
          text: "Select",
          handler: function(data) {
            return moveToBattlePage(data.id, $(_this).attr('program-id'));
          }
        }
      ]
    });
  });
  return $.each($('.rate'), function() {
    return $(this).css('color', rateToColor($(this).text()));
  });
};
