// Generated by CoffeeScript 1.6.3
var GameLog, Tutorial;

GameLog = (function() {
  function GameLog() {
    var callback, moveToBattlePage, selector;
    selector = new ProgramSelector();
    moveToBattlePage = function(playerId, enemyId) {
      return location.href = getRoot() + "combats/matching/" + playerId + "/" + enemyId;
    };
    callback = function() {
      var name, userId,
        _this = this;
      userId = getUserId();
      if (userId === parseInt($(this).attr('user-id'))) {
        bootbox.alert("自分のプログラムとは対戦できません");
        return;
      }
      name = $(".program-name", this).text();
      return selector.modal({
        title: "" + name + "と対戦するプログラムを選んで下さい",
        buttons: [
          {
            type: "success",
            text: "選択",
            handler: function(id) {
              return moveToBattlePage(id, $(_this).attr('program-id'));
            }
          }
        ]
      });
    };
    $('.battle-log-challenger').click(callback);
    $('.battle-log-defender').click(callback);
  }

  return GameLog;

})();

Tutorial = (function() {
  function Tutorial() {}

  Tutorial.prototype.start = function() {
    var msg;
    msg = "<p>CodeCombatでは、プログラミング言語OCTAGRAMを使って作成したAIをユーザ同士で戦わせます。</p>" + "<p>最強のAIを作って、ランキング上位を目指そう！</p>" + "<p>まずは、チュートリアルを見てみましょう。</p>";
    return bootbox.dialog({
      message: msg,
      title: "CodeCombatへようこそ！",
      buttons: {
        success: {
          label: "チュートリアルを見る",
          className: "btn-success",
          callback: function() {}
        },
        danger: {
          label: "今後表示しない",
          className: "btn-danger",
          callback: function() {}
        }
      }
    });
  };

  Tutorial.prototype.disableTutorial = function() {};

  return Tutorial;

})();

$(function() {
  var tutorial;
  new GameLog;
  if (tutorialEnabled) {
    tutorial = new Tutorial();
    return tutorial.start();
  }
});
