// Generated by CoffeeScript 1.6.3
var Mathing;

Mathing = (function() {
  function Mathing() {}

  Mathing.prototype.start = function(playerId, enemyId) {
    editPlayerProgram();
    return loadProgramById(playerId, function() {
      editEnemyProgram();
      return loadProgramById(enemyId, function() {
        executeProgram();
        return editPlayerProgram();
      });
    });
  };

  return Mathing;

})();

$(function() {
  var mathing, options;
  mathing = new Mathing();
  options = {
    onload: function() {
      return mathing.start(playerId, enemyId);
    },
    onend: function(result) {
      return console.log(result);
    }
  };
  return runGame(options);
});
