// Generated by CoffeeScript 1.6.3
window.onload = function() {
  var colors, converter;
  colors = ['#aaaaaa', '#5cb85c', '#428bca', '#f0ad4e', '#d9534f'];
  converter = new ColorConverter(colors);
  $.each($('.rate'), function() {
    return $(this).css('color', converter.rateToColor($(this).text()));
  });
  $.each($('.battle_num'), function() {
    return $(this).css('color', converter.battleNumToColor($(this).text()));
  });
  return $.each($('.score_average'), function() {
    return $(this).css('color', converter.scoreToColor($(this).text()));
  });
};
