// Generated by CoffeeScript 1.6.3
var Config, IS_MOBILE, SPEED;

if (typeof IS_MOBILE === "undefined" || IS_MOBILE === null) {
  IS_MOBILE = false;
} else {
  Environment.Mobile = true;
}

SPEED = 1;

(function() {
  var classes, cls, _i, _len, _results;
  classes = [enchant.model.SpriteModel, enchant.model.GroupModel];
  _results = [];
  for (_i = 0, _len = classes.length; _i < _len; _i++) {
    cls = classes[_i];
    cls.prototype.__constructor = cls.prototype.constructor;
    _results.push(cls.prototype.constructor = function() {
      if (this.properties == null) {
        this.properties = {};
      }
      Object.defineProperties(this, this.properties);
      return this.__constructor.apply(this, arguments);
    });
  }
  return _results;
})();

Config = (function() {
  function Config() {}

  Config.GAME_WIDTH = 640;

  Config.GAME_HEIGHT = 640;

  Config.GAME_OFFSET_X = 0;

  Config.GAME_OFFSET_Y = 0;

  Config.IS_MOBILE = IS_MOBILE;

  Config.EDITOR_MOBILE_SCALE_X = 0.2;

  Config.EDITOR_MOBILE_SCALE_Y = 0.2;

  Config.EDITOR_MOBILE_OFFSET_X = 640 - 128;

  Config.EDITOR_MOBILE_OFFSET_Y = 640 - 128;

  Config.OCTAGRAM_DIR = (typeof UserConfig !== "undefined" && UserConfig !== null) ? UserConfig.OCTAGRAM_DIR : "./js/octagram";

  return Config;

})();

Config.R = (function() {
  function R() {}

  R.RESOURCE_DIR = (typeof UserConfig !== "undefined" && UserConfig !== null) && (UserConfig.R != null) ? UserConfig.R.RESOURCE_DIR : "resources";

  R.MAP = {
    SRC: "" + R.RESOURCE_DIR + "/map0.png",
    BACKGROUND1: "" + R.RESOURCE_DIR + "/map/background-1.png",
    BACKGROUND_TRANSPARENT: "" + R.RESOURCE_DIR + "/map/background-transparent.png",
    BACKGROUND_MERGED: "" + R.RESOURCE_DIR + "/map/background-merged.png",
    BACKGROUND_EFFECT: "" + R.RESOURCE_DIR + "/map/background-effect.png",
    START: "" + R.RESOURCE_DIR + "/map/start.png",
    GOAL: "" + R.RESOURCE_DIR + "/map/goal.png",
    ROAD: "" + R.RESOURCE_DIR + "/map/road.png",
    WALL1_1: "" + R.RESOURCE_DIR + "/map/wall1-1.png",
    WALL1_2: "" + R.RESOURCE_DIR + "/map/wall1-2.png",
    WALL1_3: "" + R.RESOURCE_DIR + "/map/wall1-3.png",
    WALL1_4: "" + R.RESOURCE_DIR + "/map/wall1-4.png",
    WALL2_1: "" + R.RESOURCE_DIR + "/map/wall2-1.png",
    WALL2_2: "" + R.RESOURCE_DIR + "/map/wall2-2.png",
    WALL3_TOP: "" + R.RESOURCE_DIR + "/map/wall3-1.png",
    WALL3_RIGHT: "" + R.RESOURCE_DIR + "/map/wall3-2.png",
    WALL3_BOTTOM: "" + R.RESOURCE_DIR + "/map/wall3-3.png",
    WALL3_LEFT: "" + R.RESOURCE_DIR + "/map/wall3-4.png",
    WALL4: "" + R.RESOURCE_DIR + "/map/wall4.png",
    WALL5: "" + R.RESOURCE_DIR + "/map/wall5.png",
    WALL6_1: "" + R.RESOURCE_DIR + "/map/wall6-1.png",
    WALL6_2: "" + R.RESOURCE_DIR + "/map/wall6-2.png",
    WALL6_3: "" + R.RESOURCE_DIR + "/map/wall6-3.png",
    WALL6_4: "" + R.RESOURCE_DIR + "/map/wall6-4.png",
    WALL7_1: "" + R.RESOURCE_DIR + "/map/wall7-1.png",
    WALL7_2: "" + R.RESOURCE_DIR + "/map/wall7-2.png",
    WALL7_3: "" + R.RESOURCE_DIR + "/map/wall7-3.png",
    WALL7_4: "" + R.RESOURCE_DIR + "/map/wall7-4.png",
    WALL8_1: "" + R.RESOURCE_DIR + "/map/wall8-1.png",
    WALL8_2: "" + R.RESOURCE_DIR + "/map/wall8-2.png",
    WALL8_3: "" + R.RESOURCE_DIR + "/map/wall8-3.png",
    WALL8_4: "" + R.RESOURCE_DIR + "/map/wall8-4.png",
    WALL9: "" + R.RESOURCE_DIR + "/map/wall9.png",
    WALL10_1: "" + R.RESOURCE_DIR + "/map/wall10-1.png",
    WALL10_2: "" + R.RESOURCE_DIR + "/map/wall10-2.png",
    WALL10_3: "" + R.RESOURCE_DIR + "/map/wall10-3.png",
    WALL10_4: "" + R.RESOURCE_DIR + "/map/wall10-4.png"
  };

  R.CHAR = {
    CHAR0: "" + R.RESOURCE_DIR + "/chara0.png",
    CHAR1: "" + R.RESOURCE_DIR + "/chara1.png"
  };

  R.TIP = {
    ARROW: "" + R.RESOURCE_DIR + "/tip/arrow.png",
    SEARCH: "" + R.RESOURCE_DIR + "/tip/antena.png",
    TURN: "" + R.RESOURCE_DIR + "/tip/antena.png"
  };

  R.EFFECT = {
    SEARCH: "" + R.RESOURCE_DIR + "/effect/antena_anim.png"
  };

  return R;

})();
