// Generated by CoffeeScript 1.6.3
var Config, IS_MOBILE;

if (typeof IS_MOBILE === "undefined" || IS_MOBILE === null) {
  IS_MOBILE = false;
} else {
  Environment.Mobile = true;
}

(function() {
  var classes, cls, _i, _len, _results;
  classes = [enchant.model.SpriteModel, enchant.model.GroupModel];
  _results = [];
  for (_i = 0, _len = classes.length; _i < _len; _i++) {
    cls = classes[_i];
    cls.prototype.__constructor = cls.prototype.constructor;
    _results.push(cls.prototype.constructor = function() {
      if (this.properties == null) {
        this.properties = {};
      }
      Object.defineProperties(this, this.properties);
      return this.__constructor.apply(this, arguments);
    });
  }
  return _results;
})();

Config = (function() {
  function Config() {}

  Config.GAME_WIDTH = 640;

  Config.GAME_HEIGHT = 640;

  Config.GAME_OFFSET_X = 0;

  Config.GAME_OFFSET_Y = 0;

  Config.IS_MOBILE = IS_MOBILE;

  Config.EDITOR_MOBILE_SCALE_X = 0.2;

  Config.EDITOR_MOBILE_SCALE_Y = 0.2;

  Config.EDITOR_MOBILE_OFFSET_X = 640 - 128;

  Config.EDITOR_MOBILE_OFFSET_Y = 640 - 128;

  Config.OCTAGRAM_DIR = (typeof UserConfig !== "undefined" && UserConfig !== null) ? UserConfig.OCTAGRAM_DIR : "./js/octagram";

  return Config;

})();

Config.R = (function() {
  function R() {}

  R.RESOURCE_DIR = (typeof UserConfig !== "undefined" && UserConfig !== null) && (UserConfig.R != null) ? UserConfig.R.RESOURCE_DIR : "resources";

  R.MAP = {
    SRC: "" + R.RESOURCE_DIR + "/map0.png"
  };

  R.CHAR = {
    CHAR1: "" + R.RESOURCE_DIR + "/chara0.png"
  };

  R.TIP = {
    ARROW: "" + R.RESOURCE_DIR + "/tip/arrow.png",
    LIFE: "" + R.RESOURCE_DIR + "/tip/life.png",
    PICKUP_BULLET: "" + R.RESOURCE_DIR + "/tip/plus_bullet.png",
    SHOT_BULLET: "" + R.RESOURCE_DIR + "/tip/shot_bullet.png",
    SEARCH_BARRIER: "" + R.RESOURCE_DIR + "/tip/search_barrier.png",
    SEARCH_ENEMY: "" + R.RESOURCE_DIR + "/tip/search_enemy.png",
    CURRENT_DIRECT: "" + R.RESOURCE_DIR + "/tip/arrow.png",
    REST_BULLET: "" + R.RESOURCE_DIR + "/tip/rest_bullet.png",
    RANDOM_MOVE: "" + R.RESOURCE_DIR + "/tip/random_move.png",
    MOVE_TO_ENEMY: "" + R.RESOURCE_DIR + "/tip/move_to_enemy.png",
    MOVE_FROM_ENEMY: "" + R.RESOURCE_DIR + "/tip/move_from_enemy.png",
    ENERGY: "" + R.RESOURCE_DIR + "/tip/energy.png",
    REST_ENERGY_PLAYER: "" + R.RESOURCE_DIR + "/tip/rest_energy_player.png",
    REST_ENERGY_ENEMY: "" + R.RESOURCE_DIR + "/tip/rest_energy_enemy.png",
    DISTANCE: "" + R.RESOURCE_DIR + "/tip/distance.png"
  };

  return R;

})();
