// Generated by CoffeeScript 1.6.2
var Config;

Config = (function() {
  function Config() {}

  Config.GAME_WIDTH = 640;

  Config.GAME_HEIGHT = 640;

  return Config;

})();

Config.R = (function() {
  function R() {}

  R.RESOURCE_DIR = "resources";

  R.CHAR = {
    PLAYER: "" + R.RESOURCE_DIR + "/robot/player.png",
    ENEMY: "" + R.RESOURCE_DIR + "/robot/enemy.png"
  };

  R.BACKGROUND_IMAGE = {
    SPACE: "" + R.RESOURCE_DIR + "/background/background_space.png",
    HEADER: "" + R.RESOURCE_DIR + "/background/header.png",
    HP_YELLOW: "" + R.RESOURCE_DIR + "/background/hp_yellow.png",
    HP_BULE: "" + R.RESOURCE_DIR + "/background/hp_blue.png",
    HEADER_UNDER_BAR: "" + R.RESOURCE_DIR + "/background/hp_under_bar.png",
    PLATE: "" + R.RESOURCE_DIR + "/background/plate.png",
    MSGBOX: "" + R.RESOURCE_DIR + "/background/msgbox.png",
    STATUS_BOX: "" + R.RESOURCE_DIR + "/background/status_box.png",
    NEXT_BUTTON: "" + R.RESOURCE_DIR + "/background/next_button.png"
  };

  R.UI = {
    FONT0: "" + R.RESOURCE_DIR + "/ui/font0.png",
    ICON0: "" + R.RESOURCE_DIR + "/ui/icon0.png",
    PAD: "" + R.RESOURCE_DIR + "/ui/pad.png",
    APAD: "" + R.RESOURCE_DIR + "/ui/apad.png"
  };

  R.EFFECT = {
    EXPLOSION: "" + R.RESOURCE_DIR + "/effect/explosion_64x64.png"
  };

  R.BULLET = {
    ENEMY: "" + R.RESOURCE_DIR + "/bullet/bullet1.png",
    DROID: "" + R.RESOURCE_DIR + "/bullet/bullet2.png"
  };

  R.ITEM = {
    BULLET: "" + R.RESOURCE_DIR + "/item/bullet.png",
    STATUS_BULLET: "" + R.RESOURCE_DIR + "/item/status_bullet.png"
  };

  return R;

})();

Config.R.String = (function() {
  function String() {}

  String.PLAYER = "プレイヤー";

  String.ENEMY = "エネミー";

  String.CANNOTMOVE = "移動てきません";

  String.CANNOTSHOT = "弾切れです";

  String.CANNOTPICKUP = "弾を補充できません";

  String.pickup = function(s) {
    return "" + s + "は弾を一つ補充しました";
  };

  String.shot = function(s) {
    return "" + s + "は攻撃しました";
  };

  String.move = function(s, x, y) {
    return "" + s + "は(" + x + "," + y + ")に移動しました";
  };

  return String;

})();

enchant();

enchant.ui = {
  assets: ['resources/ui/pad.png', 'resources/ui/apad.png', 'resources/ui/icon0.png', 'resources/ui/font0.png']
};
