// Generated by CoffeeScript 1.3.3
var Config;

Config = (function() {

  function Config() {}

  Config.GAME_WIDTH = 640;

  Config.GAME_HEIGHT = 640;

  return Config;

})();

Config.R = (function() {

  function R() {}

  R.RESOURCE_DIR = "resources";

  R.CHAR = {
    ROBOT: "" + R.RESOURCE_DIR + "/robot/droid.png"
  };

  R.BACKGROUND_IMAGE = {
    HEADER: "" + R.RESOURCE_DIR + "/background/header.png",
    HP_YELLOW: "" + R.RESOURCE_DIR + "/background/hp_yellow.png",
    HP_BULE: "" + R.RESOURCE_DIR + "/background/hp_blue.png",
    HEADER_UNDER_BAR: "" + R.RESOURCE_DIR + "/background/hp_under_bar.png",
    TILE: "" + R.RESOURCE_DIR + "/background/tile.png",
    MSGBOX: "" + R.RESOURCE_DIR + "/background/msgbox.png",
    NEXT_BUTTON: "" + R.RESOURCE_DIR + "/background/next_button.png"
  };

  R.UI = {
    FONT0: "" + R.RESOURCE_DIR + "/ui/font0.png",
    ICON0: "" + R.RESOURCE_DIR + "/ui/icon0.png",
    PAD: "" + R.RESOURCE_DIR + "/ui/pad.png",
    APAD: "" + R.RESOURCE_DIR + "/ui/apad.png"
  };

  return R;

})();

enchant();

enchant.ui = {
  assets: ['resources/ui/pad.png', 'resources/ui/apad.png', 'resources/ui/icon0.png', 'resources/ui/font0.png']
};
