// Generated by CoffeeScript 1.6.3
var Environment;

Environment = (function() {
  function Environment() {}

  Environment.ScreenWidth = 640;

  Environment.ScreenHeight = 640;

  Environment.EditorWidth = 480;

  Environment.EditorHeight = 480;

  Environment.EditorX = 16;

  Environment.EditorY = 16;

  Environment.startX = 4;

  Environment.startY = -1;

  Environment.Mobile = false;

  return Environment;

})();

octagram.Environment = Environment;
