// Generated by CoffeeScript 1.6.3
var DEBUG, Debug;

DEBUG = true;

Debug = (function() {
  function Debug() {}

  Debug.log = function(obj) {
    return DEBUG && console.log("[AIGame Log]" + obj);
  };

  Debug.dump = function(obj) {
    return DEBUG && console.log(obj);
  };

  return Debug;

})();
