// Generated by CoffeeScript 1.6.3
var Duplicator,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Duplicator = (function() {
  function Duplicator() {}

  Duplicator.copyOctagramObject = function(local) {
    var ignores, key, value, _ref, _results;
    ignores = ['Resources', 'TipUtil'];
    _ref = local.parent.octagram;
    _results = [];
    for (key in _ref) {
      value = _ref[key];
      if (!(__indexOf.call(ignores, key) >= 0)) {
        console.log('duplicate : ' + 'octagram.' + key);
        _results.push(local[key] = value);
      } else {
        _results.push(console.log('ignore : ' + 'octagram.' + key));
      }
    }
    return _results;
  };

  return Duplicator;

})();
