// Generated by CoffeeScript 1.6.3
window.onload = function() {
  var core,
    _this = this;
  core = new this.OctagramCore(16, 16, 640, 640, "./resource/");
  core.start();
  core.onload = function() {
    var program, scene;
    scene = new Scene(core);
    core.pushScene(scene);
    program = core.octagrams.createInstance();
    return core.octagrams.show(program.id);
  };
  this.octagram.core = core;
  return this.octagram.onload();
};
