// Generated by CoffeeScript 1.6.2
var Environment, GlobalUI, LayerOrder, TipBasedVPL, TipTable, board, executer,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

board = null;

executer = null;

Environment = (function() {
  function Environment() {}

  Environment.ScreenWidth = 640;

  Environment.ScreenHeight = 640;

  Environment.EditorWidth = 480;

  Environment.EditorHeight = 480;

  Environment.EditorX = 16;

  Environment.EditorY = 16;

  Environment.startX = 4;

  Environment.startY = -1;

  return Environment;

})();

LayerOrder = (function() {
  function LayerOrder() {}

  LayerOrder.background = 10;

  LayerOrder.transition = 15;

  LayerOrder.tip = 20;

  LayerOrder.tipIcon = 21;

  LayerOrder.tipEffect = 22;

  LayerOrder.frame = 30;

  LayerOrder.frameUI = 31;

  LayerOrder.frameUIIcon = 32;

  LayerOrder.frameUIArrow = 33;

  LayerOrder.frameUIEffect = 34;

  LayerOrder.messageWindow = 40;

  LayerOrder.messageText = 45;

  LayerOrder.dialog = 50;

  LayerOrder.dialogButton = 55;

  LayerOrder.dialogUI = 56;

  LayerOrder.dialogText = 57;

  LayerOrder.dialogIcon = 58;

  LayerOrder.dialogEffect = 59;

  LayerOrder.top = 100;

  return LayerOrder;

})();

GlobalUI = (function() {
  function GlobalUI() {}

  GlobalUI.frame;

  GlobalUI.help;

  GlobalUI.configPanel;

  GlobalUI.side;

  return GlobalUI;

})();

TipTable = (function() {
  function TipTable() {}

  TipTable.tips = [];

  TipTable.addTip = function(tip, icon) {
    if (icon != null) {
      tip.setIcon(new Icon(icon));
    }
    return this.tips.push(tip);
  };

  TipTable.addInstruction = function(inst, icon) {
    var tip;

    tip = TipFactory.createInstructionTip(inst);
    if (icon != null) {
      tip.setIcon(new Icon(icon));
    }
    return TipTable.addTip(tip);
  };

  return TipTable;

})();

TipBasedVPL = (function(_super) {
  __extends(TipBasedVPL, _super);

  function TipBasedVPL(w, h, resourceBase) {
    TipBasedVPL.__super__.constructor.call(this, w, h);
    this.fps = 24;
    Resources.base = resourceBase;
    Resources.load(this);
  }

  TipBasedVPL.prototype.addInstruction = function(instruction, icon) {
    return TipTable.addInstruction(instruction, icon);
  };

  TipBasedVPL.prototype.addPresetInstructions = function() {
    var inst, nopTip, returnTip, stopTip;

    returnTip = TipFactory.createReturnTip(Environment.startX, Environment.startY);
    stopTip = TipFactory.createStopTip();
    nopTip = TipFactory.createNopTip();
    inst = new RandomBranchInstruction();
    TipTable.addInstruction(inst, Resources.get("iconRandom"));
    TipTable.addTip(returnTip);
    TipTable.addTip(stopTip);
    return TipTable.addTip(nopTip, Resources.get("iconNop"));
  };

  TipBasedVPL.prototype.clearInstructions = function() {
    return this.tips = [];
  };

  TipBasedVPL.prototype.loadInstruction = function() {
    var tip, _i, _len, _ref;

    this.clearInstructions();
    this.addPresetInstructions();
    _ref = TipTable.tips;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tip = _ref[_i];
      GlobalUI.side.addTip(tip);
    }
    return GlobalUI.side.show();
  };

  TipBasedVPL.prototype.onload = function() {
    var back, selector, x, xnum, y, ynum;

    x = 16;
    y = 16;
    xnum = 8;
    ynum = 8;
    back = new TipBackground(x, y, xnum, ynum);
    board = new Cpu(x + 12, y + 12, xnum, ynum, Environment.startX);
    executer = new Executer(board);
    GlobalUI.frame = new Frame(0, 0);
    GlobalUI.help = new HelpPanel(0, Environment.EditorHeight + y, Environment.ScreenWidth, Environment.ScreenWidth - Environment.EditorWidth - x, "");
    GlobalUI.frame.show();
    GlobalUI.help.show();
    selector = new ParameterConfigPanel(Environment.EditorWidth + x / 2, 0);
    GlobalUI.side = new SideTipSelector(Environment.EditorWidth + x / 2, 0);
    GlobalUI.configPanel = new UIPanel(selector);
    GlobalUI.configPanel.setTitle(TextResource.msg.title["configurator"]);
    return selector.parent = GlobalUI.configPanel;
  };

  return TipBasedVPL;

})(Game);
