// Generated by CoffeeScript 1.6.3
var Environment, TipBasedVPL, TipTable,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Environment = (function() {
  function Environment() {}

  Environment.ScreenWidth = 640;

  Environment.ScreenHeight = 640;

  Environment.EditorWidth = 480;

  Environment.EditorHeight = 480;

  Environment.EditorX = 16;

  Environment.EditorY = 16;

  Environment.startX = 4;

  Environment.startY = -1;

  return Environment;

})();

TipTable = (function() {
  function TipTable() {}

  TipTable.tips = [];

  TipTable.clear = function() {
    return this.tips = [];
  };

  TipTable.addTip = function(tip) {
    return this.tips.push(tip);
  };

  TipTable.addInstruction = function(inst) {
    var tip;
    tip = TipFactory.createInstructionTip(inst);
    return TipTable.addTip(tip);
  };

  return TipTable;

})();

TipBasedVPL = (function(_super) {
  __extends(TipBasedVPL, _super);

  function TipBasedVPL(w, h, resourceBase) {
    TipBasedVPL.__super__.constructor.call(this, w, h);
    this.fps = 24;
    Resources.base = resourceBase;
    Resources.load(this);
  }

  TipBasedVPL.prototype.addInstruction = function(instruction) {
    return TipTable.addInstruction(instruction);
  };

  TipBasedVPL.prototype.addPresetInstructions = function() {
    var inst, nopTip, returnTip, stopTip;
    returnTip = TipFactory.createReturnTip(Environment.startX, Environment.startY);
    stopTip = TipFactory.createStopTip();
    nopTip = TipFactory.createNopTip();
    inst = new RandomBranchInstruction();
    TipTable.addInstruction(inst, Resources.get("iconRandom"));
    TipTable.addTip(returnTip);
    TipTable.addTip(stopTip);
    return TipTable.addTip(nopTip, Resources.get("iconNop"));
  };

  TipBasedVPL.prototype.clearInstructions = function() {
    return TipTable.clear();
  };

  TipBasedVPL.prototype.loadInstruction = function() {
    var tip, _i, _len, _ref, _results;
    this.addPresetInstructions();
    _ref = TipTable.tips;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tip = _ref[_i];
      _results.push(Game.instance.vpl.ui.side.addTip(tip));
    }
    return _results;
  };

  TipBasedVPL.prototype.onload = function() {
    var back, selector, x, xnum, y, ynum;
    x = 16;
    y = 16;
    xnum = 8;
    ynum = 8;
    back = new TipBackground(x, y, xnum, ynum);
    Game.instance.vpl = {};
    Game.instance.vpl.ui = {};
    Game.instance.vpl.cpu = new Cpu(x + 12, y + 12, xnum, ynum, Environment.startX);
    Game.instance.vpl.executer = new Executer(Game.instance.vpl.cpu);
    Game.instance.vpl.ui.frame = new Frame(0, 0);
    Game.instance.vpl.ui.help = new HelpPanel(0, Environment.EditorHeight + y, Environment.ScreenWidth, Environment.ScreenWidth - Environment.EditorWidth - x, "");
    selector = new ParameterConfigPanel(Environment.EditorWidth + x / 2, 0);
    Game.instance.vpl.ui.side = new SideTipSelector(Environment.EditorWidth + x / 2, 0);
    Game.instance.vpl.ui.configPanel = new UIPanel(selector);
    Game.instance.vpl.ui.configPanel.setTitle(TextResource.msg.title["configurator"]);
    selector.parent = Game.instance.vpl.ui.configPanel;
    Game.instance.currentScene.addChild(back);
    Game.instance.currentScene.addChild(Game.instance.vpl.cpu);
    Game.instance.currentScene.addChild(Game.instance.vpl.ui.frame);
    Game.instance.currentScene.addChild(Game.instance.vpl.ui.side);
    return Game.instance.currentScene.addChild(Game.instance.vpl.ui.help);
  };

  return TipBasedVPL;

})(Game);
