// Generated by CoffeeScript 1.6.2
var EventUtil, LayerUtil, TipUtil;

TipUtil = (function() {
  function TipUtil() {}

  TipUtil.tipToImage = function(code) {
    var assetName;

    assetName = code instanceof EmptyTip ? "emptyTip" : code instanceof ReturnTip ? "returnTip" : code instanceof StartTip ? "startTip" : code instanceof StopTip ? "stopTip" : code instanceof ActionTip ? "actionTip" : code instanceof BranchTip ? "branchTip" : code instanceof ThinkTip ? "thinkTip" : code instanceof WallTip ? "wallTip" : void 0;
    return Resources.get(assetName);
  };

  TipUtil.tipToIcon = function(code) {
    if (code instanceof NopTip) {
      return Resources.get("iconNop");
    }
  };

  TipUtil.tipToMessage = function(code) {
    if (code instanceof EmptyTip) {
      return TextResource.msg["empty"];
    } else if (code instanceof ReturnTip) {
      return TextResource.msg["return"];
    } else if (code instanceof StartTip) {
      return TextResource.msg["start"];
    } else if (code instanceof StopTip) {
      return TextResource.msg["stop"];
    } else if (code instanceof ActionTip) {
      return TextResource.msg["action"];
    } else if (code instanceof BranchTip) {
      return TextResource.msg["branch"];
    } else if (code instanceof WallTip) {
      return TextResource.msg["wall"];
    } else if (code instanceof NopTip) {
      return TextResource.msg["nop"];
    }
  };

  return TipUtil;

})();

LayerUtil = (function() {
  function LayerUtil() {}

  /*
  @initialize : (@layerNum) ->
    @layers = []
    for i in [0..@layerNum]
      layer = new Group()
      LayerUtil.layers.push(layer)
      Game.instance.currentScene.addChild(layer)
  */


  LayerUtil.setOrder = function(obj, order) {
    /*
    obj._element = document.createElement("div") if !obj._element?
    obj._element.style.zIndex = order
    */

  };

  return LayerUtil;

})();

EventUtil = (function() {
  function EventUtil() {}

  EventUtil.prototype.createEvent = function(eventName) {
    var evt;

    evt = document.createEvent('UIEvent', false);
    evt.initUIEvent(eventName, true, true);
    return evt;
  };

  return EventUtil;

})();

/*
clone = (src) ->
  if src?
    if src.constructor is String then return src
    ret = 
      if src.constructor is Array then []
      else if src.constructor is Object then {}
      else src#src.constructor()
    #if !ret? then ret = src

    for key of src
      ret[key] = clone(src[key])

    ret
*/

